### ISSUE TITLE
Getting "404 Not Found"

### ISSUE THREAD

**Issue by thomthom** [gverschuur/laravel-robotstxt#1]
Got a Laravel 5.2 app.

Used `composer require gverschuur/laravel-robotstxt`, added `Gverschuur\RobotsTxt\RobotsTxtProvider::class` to `config/app.php`

I removed the pre-existing `public/robots.txt` file.

`php artisan route:list` shows:

`GET|HEAD | robots.txt                                   | robots.txt                     | Gverschuur\RobotsTxt\Controllers\RobotsTxtController@index`

But when I try to access the file in the browser on my Homestead box it yields an nginx 404 error, not even the normal Laravel error handler kicks in.

```
404 Not Found

nginx/1.8.0
```

Any ideas?

**Comment by gverschuur** [comment]
Sorry, but I have zero experience with nginx servers (nor have I tested it on nginx) :( 

I have no idea why it throws a 404, it should just hook into the Laravel lifecycle. If you use a regular robots.txt, does it load that one correctly?

Also, apologies for the late reply, I didn't get a notification from github that someone had opened an issue.

**Comment by thomthom** [comment]
Sorry for not messaging back. It turns out that nginx config on Forge have a default setup where robot.txt doesn't pass by the Laravel app. It serves it directly without access logging etc because the file is hit so many times.
I haven't figured out the best way to address that yet. I can remove the line in nginx config, but then I get the extra logging its trying to avoid. Haven't figured out if that's much of an issue. Need to ponder more about this and learn more about nginx. So far I've not customized nginx  which I prefer, as it's less maintenance for me.

**Comment by gverschuur** [comment]
Ok, thanks for letting me know. I'll update the readme with this little bit of info.

**Comment by brynnb** [comment]
Many years later I ran into this too when trying to test locally with vagrant (which I assume is setup the same as Forge). Works fine with deployed to Heroku though.
